config/routes.rb
Rails::Application.routes.draw do
  resources :vcards
end

app/models/vcard.rb
class Vcard < ActiveRecord::Base
  include VisitCard::Models::Vcard
end

app/models/vcard_adr.rb
class VcardAdr < ActiveRecord::Base
  include VisitCard::Models::VcardAdr
end

app/models/vcard_categorization.rb
class VcardCategorization < ActiveRecord::Base
  include VisitCard::Models::VcardCategorization
end

app/models/vcard_dictionary.rb
class VcardDictionary < ActiveRecord::Base
  include VisitCard::Models::VcardDictionary
end

app/models/vcard_email.rb
class VcardEmail < ActiveRecord::Base
  include VisitCard::Models::VcardEmail
end

app/models/vcard_extension.rb
class VcardExtension < ActiveRecord::Base
  include VisitCard::Models::VcardExtension
end

app/models/vcard_tel.rb
class VcardTel < ActiveRecord::Base
  include VisitCard::Models::VcardTel
end

app/controllers/vcards_controller.rb
class VcardsController < ApplicationController
  include VisitCard::Controllers::VcardsController
end

app/helpers/vcards_helper.rb
module VcardsHelper
  include VisitCard::Helpers::VcardsHelper
end

app/views/visit_card/vcard_adrs/_form_fields.html.erb
<fieldset class="inputs adr">
  <legend>Address</legend>
  <ol>
    <li class="field">
      <%= ff.check_box_collection :types, VisitCard.adr_types %>
    </li>
    <li class="field">
      <%= ff.label :post_office_box %>
      <%= ff.text_field :post_office_box %>
    </li>
    <li class="field">
      <%= ff.label :extended_address %>
      <%= ff.text_field :extended_address %>
    </li>
    <li class="field">
      <%= ff.label :street_address %>
      <%= ff.text_field :street_address %>
    </li>
    <li class="field">
      <%= ff.label :locality %>
      <%= ff.text_field :locality %>
    </li>
    <li class="field">
      <%= ff.label :region %>
      <%= ff.text_field :region %>
    </li>
    <li class="field">
      <%= ff.label :postal_code %>
      <%= ff.text_field :postal_code %>
    </li>
    <li class="field">
      <%= ff.label :country_name %>
      <%= ff.respond_to?(:country_select) ? ff.country_select(:country_name, [], :include_blank => true) : ff.text_field(:country_name) 
      %>
    </li>
  </ol>
  <%= ff.hidden_field :_destroy, :value => '' %>
  <a href='#' class='remove'>Remove</a>
</fieldset>

app/views/visit_card/vcard_emails/_form_fields.html.erb
<fieldset class="inputs email">
  <legend>Email</legend>
  <ol>
    <li class="field">
      <%= ff.check_box_collection :types, VisitCard.email_types %>
    </li>
    <li class="field">
      <%= ff.label :value %>
      <%= ff.email_field :value %>
    </li>
  </ol>
  <%= ff.hidden_field :_destroy, :value => '' %>
  <a href='#' class='remove'>Remove</a>
</fieldset>

app/views/visit_card/vcard_extensions/_form_fields.html.erb
<fieldset class="inputs extension">
  <legend>Extension</legend>
  <ol>
    <li class="field">
      <%= ff.check_box_collection :types, VisitCard.extension_types %>
    </li>
    <li class="field">
      <%= ff.label :vcard_extension_type %>
      <%= ff.select :vcard_dictionary_id, VcardDictionary.extension_types.map{|e| [e.name, e.id]} %>
    </li>
    <li class="field">
      <%= ff.label :value %>
      <%= ff.text_field :value %>
    </li>
  </ol>
  <%= ff.hidden_field :_destroy, :value => '' %>
  <a href='#' class='remove'>Remove</a>
</fieldset>

app/views/visit_card/vcard_extentions/_form_fields.html.erb
<fieldset class="inputs extention">
  <legend>Extention</legend>
  <ol>
    <li class="field">
      <%= ff.check_box_collection :types, VcardExtention::TYPES %>
    </li>
    <li class="field">
      <%= ff.label :vcard_extention_type %>
      <%= ff.select :vcard_dictionary_id, VcardDictionary.extention_types.map{|e| [e.name, e.id]} %>
    </li>
    <li class="field">
      <%= ff.label :value %>
      <%= ff.text_field :value %>
    </li>
  </ol>
  <%= ff.hidden_field :_destroy, :value => '' %>
  <a href='#' class='remove'>Remove</a>
</fieldset>

app/views/visit_card/vcard_tels/_form_fields.html.erb
<fieldset class="inputs tel">
  <legend>Telephone</legend>
  <ol>
    <li class="field">
      <%= ff.check_box_collection :types, VisitCard.tel_types %>
    </li>
    <li class="field">
      <%= ff.label :value %>
      <%= ff.telephone_field :value %>
    </li>
  </ol>
  <%= ff.hidden_field :_destroy, :value => '' %>
  <a href='#' class='remove'>Remove</a>
</fieldset>

app/views/visit_card/vcards/_form.html.erb
<%= render 'static' %>
<%= form_for @vcard do |f| %>
  <% if @vcard.errors.any? %>
    <div id="errorExplanation">
      <h2><%= "#{pluralize(@vcard.errors.count, "error")} prohibited this project from being saved:"%></h2>
      <ul>
        <% @vcard.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <fieldset class="inputs">
    <ol>
      <li class="field required">
        <%= f.label :family_name %>
        <%= f.text_field :family_name %>
      </li>
      <li class="field required">
        <%= f.label :given_name %>
        <%= f.text_field :given_name %>
      </li>
      <li class="field">
        <%= f.label :additional_name %>
        <%= f.text_field :additional_name %>
      </li>
      <li class="field">
        <%= f.label :honorific_prefix %>
        <%= f.text_field :honorific_prefix, :size => 10, :maxlength => 10 %>
      </li>
      <li class="field">
        <%= f.label :honorific_suffix %>
        <%= f.text_field :honorific_suffix, :size => 10, :maxlength => 10 %>
      </li>
      <li class="field">
        <%= f.label :nickname %>
        <%= f.text_field :nickname %>
      </li>
      <li class="field">
        <%= f.label :photo %>
        <%= f.url_field :photo %>
      </li>
      <li class="field">
        <%= f.label :bday %>
        <%= f.date_select :bday, :start_year => Time.now.year - 80, :end_year => Time.now.year, :include_blank => true %>
      </li>

      <li class="field">
        <%= f.label :mailer %>
        <%= f.text_field :mailer %>
      </li>
      <li class="field">
        <%= f.label :tz %>
        <%= f.time_zone_select :tz, nil, :include_blank => true %>
      </li>
      <li class="field">
        <%= f.label :latitude %>
        <%= f.number_field :latitude, :size => 10, :maxlength => 10 %>
      </li>
      <li class="field">
        <%= f.label :longitude %>
        <%= f.number_field :longitude, :size => 10, :maxlength => 10 %>
      </li>
      <li class="field">
        <%= f.label :title %>
        <%= f.text_field :title %>
      </li>
      <li class="field">
        <%= f.label :role %>
        <%= f.text_field :role %>
      </li>
      <li class="field">
        <%= f.label :logo %>
        <%= f.url_field :logo %>
      </li>
      <li class="field">
        <%= f.label :agent %>
        <%= f.select :agent_id, Vcard.except(params[:id]).collect {|v| [ v.fga, v.id ] }, :include_blank => true %>
      </li>
      <li class="field required">
        <%= f.label :organization_name %>
        <%= f.text_field :organization_name %>
      </li>
      <li class="field">
        <%= f.label :organization_unit %>
        <%= f.text_field :organization_unit %>
      </li>
      <li class="field">
        <%= f.check_box_collection :vcard_categories, Hash[ *VcardDictionary.categories.collect { |d| [ d.id, d.name ] }.flatten ] %>
      </li>
      <li class="field">
        <%= f.label :note %>
        <%= f.text_area :note %>
      </li>
      <li class="field">
        <%= f.label :sort_string %>
        <%= f.text_field :sort_string %>
      </li>
      <li class="field">
        <%= f.label :sound %>
        <%= f.text_field :sound %>
      </li>
      <li class="field">
        <%= f.label :uid %>
        <%= f.text_field :uid %>
      </li>
      <li class="field">
        <%= f.label :url %>
        <%= f.url_field :url %>
      </li>
      <li class="field">
        <%= f.label :klass %>
        <%= f.select :klass, VisitCard.klasses %>
      </li>
      <li class="field">
        <%= f.label :key %>
        <%= f.text_field :key %>
      </li>

      <% %w{adrs tels emails extensions}.each do |item| %>
        <li class="field <%= item %>">
          <%= f.fields_for :"vcard_#{item}" do |ff| %>
            <%= render "vcard_#{item}/form_fields", :ff => ff %>
          <% end %>
          <a href='#' class='add' title='<%= item.singularize %>'>Add <%= item.singularize.humanize %></a>
        </li>
      <% end %>
    </ol>
  </fieldset>
  
  <fieldset class="buttons">
    <ol>
      <li class="actions">
        <%= f.submit 'Save' %>
      </li>
    </ol>
  </fieldset>
<% end %>

app/views/visit_card/vcards/_hcard.html.erb
<%= @vcard.to_hcard %>

app/views/visit_card/vcards/edit.html.erb
<h1>Edit VCard</h1>

<%= render 'form' %>

<p>
  <%= link_to 'Back', vcards_path %>
</p>

app/views/visit_card/vcards/index.html.erb
<h1>Listing VCards</h1>

<table>
  <tr>
    <th>FN</th>
    <th>Action</th>
  </tr>
<% @vcards.each do |vcard| %>
  <tr>
    <td><%= link_to(vcard.fga, vcard) %></td>
    <td><%= link_to 'Edit', edit_vcard_path(vcard) %> | <%= link_to 'Destroy', vcard, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<p>
  <%= link_to 'New VCard', new_vcard_path %>
</p>

app/views/visit_card/vcards/new.html.erb
<h1>New VCard</h1>

<%= render 'form' %>

<p>
  <%= link_to 'Back', vcards_path %>
</p>

app/views/visit_card/vcards/show.html.erb
<h1><%= @vcard.fn << (@vcard.nickname? ? " (#{@vcard.nickname})" : '') %></h1>

<%= render 'hcard' %>

<p>
  <%= link_to 'Edit', edit_vcard_path(@vcard) %> | <%= link_to 'Back', vcards_path %>
</p>